import Project.ConnectionProvider;
import java.sql.*;
import javax.swing.JOptionPane;
/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author user
 */
public class addNewPatientRecord extends javax.swing.JFrame {

    /**
     * Creates new form addNewPatientRecord
     */
    public addNewPatientRecord() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        closeAddNewRecord = new javax.swing.JButton();
        patientID = new javax.swing.JLabel();
        namePatient = new javax.swing.JLabel();
        contactNo = new javax.swing.JLabel();
        patientAge = new javax.swing.JLabel();
        patientGender = new javax.swing.JLabel();
        addresssPatientLabel = new javax.swing.JLabel();
        anyDiseaseEarlier = new javax.swing.JLabel();
        patientBloodGroup = new javax.swing.JLabel();
        patientIdField = new javax.swing.JTextField();
        patientName = new javax.swing.JTextField();
        patientContactNumber = new javax.swing.JTextField();
        genderPatientField = new javax.swing.JComboBox<>();
        patientAgeField = new javax.swing.JTextField();
        bloodGroupField = new javax.swing.JComboBox<>();
        addressPatientField = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        anyMajorDiseaseField = new javax.swing.JTextArea();
        sumbitButton = new javax.swing.JButton();
        formBackground = new javax.swing.JLabel();

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rsz_form_background.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(350, 250));
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        closeAddNewRecord.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 14)); // NOI18N
        closeAddNewRecord.setForeground(new java.awt.Color(102, 102, 102));
        closeAddNewRecord.setIcon(new javax.swing.ImageIcon(getClass().getResource("/clsoe.png"))); // NOI18N
        closeAddNewRecord.setText("Close");
        closeAddNewRecord.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeAddNewRecordActionPerformed(evt);
            }
        });
        getContentPane().add(closeAddNewRecord, new org.netbeans.lib.awtextra.AbsoluteConstraints(632, 518, 130, 50));

        patientID.setFont(new java.awt.Font("MS Reference Sans Serif", 0, 14)); // NOI18N
        patientID.setForeground(new java.awt.Color(102, 102, 102));
        patientID.setText("Patient ID");
        getContentPane().add(patientID, new org.netbeans.lib.awtextra.AbsoluteConstraints(217, 70, -1, 26));

        namePatient.setFont(new java.awt.Font("MS Reference Sans Serif", 0, 14)); // NOI18N
        namePatient.setForeground(new java.awt.Color(102, 102, 102));
        namePatient.setText("Name");
        getContentPane().add(namePatient, new org.netbeans.lib.awtextra.AbsoluteConstraints(242, 114, -1, -1));

        contactNo.setFont(new java.awt.Font("MS Reference Sans Serif", 0, 14)); // NOI18N
        contactNo.setForeground(new java.awt.Color(102, 102, 102));
        contactNo.setText("Contact No");
        getContentPane().add(contactNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(207, 158, -1, -1));

        patientAge.setFont(new java.awt.Font("MS Reference Sans Serif", 0, 14)); // NOI18N
        patientAge.setForeground(new java.awt.Color(102, 102, 102));
        patientAge.setText("Age");
        getContentPane().add(patientAge, new org.netbeans.lib.awtextra.AbsoluteConstraints(255, 202, -1, -1));

        patientGender.setFont(new java.awt.Font("MS Reference Sans Serif", 0, 14)); // NOI18N
        patientGender.setForeground(new java.awt.Color(102, 102, 102));
        patientGender.setText("Gender");
        getContentPane().add(patientGender, new org.netbeans.lib.awtextra.AbsoluteConstraints(234, 249, -1, -1));

        addresssPatientLabel.setFont(new java.awt.Font("MS Reference Sans Serif", 0, 14)); // NOI18N
        addresssPatientLabel.setForeground(new java.awt.Color(102, 102, 102));
        addresssPatientLabel.setText("Address");
        getContentPane().add(addresssPatientLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 340, -1, -1));

        anyDiseaseEarlier.setFont(new java.awt.Font("MS Reference Sans Serif", 0, 14)); // NOI18N
        anyDiseaseEarlier.setForeground(new java.awt.Color(102, 102, 102));
        anyDiseaseEarlier.setText("Any Major Disease  Suffered Earlier");
        getContentPane().add(anyDiseaseEarlier, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 378, -1, -1));

        patientBloodGroup.setFont(new java.awt.Font("MS Reference Sans Serif", 0, 14)); // NOI18N
        patientBloodGroup.setForeground(new java.awt.Color(102, 102, 102));
        patientBloodGroup.setText("Blood Group");
        patientBloodGroup.setToolTipText("");
        getContentPane().add(patientBloodGroup, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 296, -1, -1));

        patientIdField.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        getContentPane().add(patientIdField, new org.netbeans.lib.awtextra.AbsoluteConstraints(324, 70, 187, -1));

        patientName.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        getContentPane().add(patientName, new org.netbeans.lib.awtextra.AbsoluteConstraints(324, 114, 187, -1));

        patientContactNumber.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        patientContactNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                patientContactNumberActionPerformed(evt);
            }
        });
        getContentPane().add(patientContactNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(324, 158, 187, -1));

        genderPatientField.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        genderPatientField.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Male", "Female", "Other", " " }));
        genderPatientField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                genderPatientFieldActionPerformed(evt);
            }
        });
        getContentPane().add(genderPatientField, new org.netbeans.lib.awtextra.AbsoluteConstraints(324, 246, 187, -1));

        patientAgeField.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        patientAgeField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                patientAgeFieldActionPerformed(evt);
            }
        });
        getContentPane().add(patientAgeField, new org.netbeans.lib.awtextra.AbsoluteConstraints(324, 202, 187, -1));

        bloodGroupField.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        bloodGroupField.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "A+", "A-", "B+", "B-", "O+", "O-", "AB+", "AB-" }));
        getContentPane().add(bloodGroupField, new org.netbeans.lib.awtextra.AbsoluteConstraints(324, 290, 187, -1));

        addressPatientField.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        addressPatientField.setToolTipText("");
        getContentPane().add(addressPatientField, new org.netbeans.lib.awtextra.AbsoluteConstraints(324, 334, 187, -1));

        anyMajorDiseaseField.setColumns(20);
        anyMajorDiseaseField.setRows(5);
        jScrollPane1.setViewportView(anyMajorDiseaseField);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(285, 405, -1, -1));

        sumbitButton.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 14)); // NOI18N
        sumbitButton.setForeground(new java.awt.Color(102, 102, 102));
        sumbitButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/submit.png"))); // NOI18N
        sumbitButton.setText("Sumbit");
        sumbitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sumbitButtonActionPerformed(evt);
            }
        });
        getContentPane().add(sumbitButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 510, 190, 50));

        formBackground.setFont(new java.awt.Font("MS Reference Sans Serif", 0, 14)); // NOI18N
        formBackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rsz_form_background.jpg"))); // NOI18N
        getContentPane().add(formBackground, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 780, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void closeAddNewRecordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeAddNewRecordActionPerformed
        // TODO add your handling code here:
        setVisible(false);
    }//GEN-LAST:event_closeAddNewRecordActionPerformed

    private void genderPatientFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_genderPatientFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_genderPatientFieldActionPerformed

    private void patientAgeFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_patientAgeFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_patientAgeFieldActionPerformed

    private void sumbitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sumbitButtonActionPerformed
        // TODO add your handling code here:
        String patientID = patientIdField.getText();
        String name = patientName.getText();
        String contactNo = patientContactNumber.getText();
        String age =  patientAgeField.getText();
        String gender =(String)genderPatientField .getSelectedItem();
        String bloodGroup =(String)bloodGroupField.getSelectedItem();
        String address =   addressPatientField.getText();  
        String anyMajorDiseases = anyMajorDiseaseField .getText();
         try
         {
             Connection con = ConnectionProvider.getCon();
             Statement st = con.createStatement();
             st.executeUpdate("insert into patient values ('"+patientID+"','"+name+"','"+contactNo+"','"+age+"','"+gender+"','"+bloodGroup+"','"+address+"','"+ anyMajorDiseases +"')");
             JOptionPane.showMessageDialog(null,"Successfully Sumbitted");
             setVisible(false);
             new addNewPatientRecord().setVisible(true);
             
         }
         catch(SQLException e)
                 {
                                  JOptionPane.showMessageDialog(null,"Please Enter Data In Correct Format");

                 }
        
    }//GEN-LAST:event_sumbitButtonActionPerformed

    private void patientContactNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_patientContactNumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_patientContactNumberActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(addNewPatientRecord.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(addNewPatientRecord.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(addNewPatientRecord.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(addNewPatientRecord.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new addNewPatientRecord().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField addressPatientField;
    private javax.swing.JLabel addresssPatientLabel;
    private javax.swing.JLabel anyDiseaseEarlier;
    private javax.swing.JTextArea anyMajorDiseaseField;
    private javax.swing.JComboBox<String> bloodGroupField;
    private javax.swing.JButton closeAddNewRecord;
    private javax.swing.JLabel contactNo;
    private javax.swing.JLabel formBackground;
    private javax.swing.JComboBox<String> genderPatientField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel namePatient;
    private javax.swing.JLabel patientAge;
    private javax.swing.JTextField patientAgeField;
    private javax.swing.JLabel patientBloodGroup;
    private javax.swing.JTextField patientContactNumber;
    private javax.swing.JLabel patientGender;
    private javax.swing.JLabel patientID;
    private javax.swing.JTextField patientIdField;
    private javax.swing.JTextField patientName;
    private javax.swing.JButton sumbitButton;
    // End of variables declaration//GEN-END:variables
}
