
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author user
 */
public class home extends javax.swing.JFrame {

    /**
     * Creates new form home
     */
    public home() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        backgroundHome = new javax.swing.JLabel();
        addressButton = new javax.swing.JButton();
        updateButton = new javax.swing.JButton();
        exitButton = new javax.swing.JButton();
        addPaitentButton = new javax.swing.JButton();
        hospitalInfo = new javax.swing.JButton();
        historyPatient = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        backgroundHome.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        backgroundHome.setForeground(new java.awt.Color(102, 102, 102));
        backgroundHome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/home_background.jpg"))); // NOI18N
        backgroundHome.setText("p");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        addressButton.setFont(new java.awt.Font("MS Reference Sans Serif", 0, 14)); // NOI18N
        addressButton.setForeground(new java.awt.Color(102, 102, 102));
        addressButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/informationDignosis.png"))); // NOI18N
        addressButton.setText("     Add Diagnosis Information");
        addressButton.setToolTipText("");
        getContentPane().add(addressButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 240, 320, 70));

        updateButton.setFont(new java.awt.Font("MS Reference Sans Serif", 0, 14)); // NOI18N
        updateButton.setForeground(new java.awt.Color(102, 102, 102));
        updateButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/update-user.png"))); // NOI18N
        updateButton.setText("   Update Patient Record");
        updateButton.setToolTipText("");
        updateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateButtonActionPerformed(evt);
            }
        });
        getContentPane().add(updateButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 450, 320, 60));

        exitButton.setFont(new java.awt.Font("MS Reference Sans Serif", 0, 14)); // NOI18N
        exitButton.setForeground(new java.awt.Color(102, 102, 102));
        exitButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/exit-sign.png"))); // NOI18N
        exitButton.setText("      Log Out Account ");
        exitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitButtonActionPerformed(evt);
            }
        });
        getContentPane().add(exitButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 660, 320, 60));

        addPaitentButton.setFont(new java.awt.Font("MS Reference Sans Serif", 0, 14)); // NOI18N
        addPaitentButton.setForeground(new java.awt.Color(102, 102, 102));
        addPaitentButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/add-paitent.png"))); // NOI18N
        addPaitentButton.setText("      Add Paitent Details  ");
        addPaitentButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addPaitentButtonActionPerformed(evt);
            }
        });
        getContentPane().add(addPaitentButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, 320, 70));

        hospitalInfo.setFont(new java.awt.Font("MS Reference Sans Serif", 0, 14)); // NOI18N
        hospitalInfo.setForeground(new java.awt.Color(102, 102, 102));
        hospitalInfo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/about.png"))); // NOI18N
        hospitalInfo.setText("Hospital Information");
        hospitalInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hospitalInfoActionPerformed(evt);
            }
        });
        getContentPane().add(hospitalInfo, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 550, 320, 60));

        historyPatient.setFont(new java.awt.Font("MS Reference Sans Serif", 0, 14)); // NOI18N
        historyPatient.setForeground(new java.awt.Color(102, 102, 102));
        historyPatient.setIcon(new javax.swing.ImageIcon(getClass().getResource("/medical_history.png"))); // NOI18N
        historyPatient.setText("Full History Of Patient");
        historyPatient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                historyPatientActionPerformed(evt);
            }
        });
        getContentPane().add(historyPatient, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 340, 320, 70));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/home_background.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitButtonActionPerformed
        // TODO add your handling code here:
       int a =JOptionPane.showConfirmDialog(null,"Do You Really Want To Log Out","Select",JOptionPane.YES_NO_OPTION);
        if(a==0)
        {    
            setVisible(false);
            new login().setVisible(true);
        }   
    }//GEN-LAST:event_exitButtonActionPerformed

    private void historyPatientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_historyPatientActionPerformed
        // TODO add your handling code here:
        new fullHistoryOfPatient().setVisible(true);
    }//GEN-LAST:event_historyPatientActionPerformed

    private void addPaitentButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addPaitentButtonActionPerformed
        // TODO add your handling code here:
        new addNewPatientRecord().setVisible(true);
    }//GEN-LAST:event_addPaitentButtonActionPerformed

    private void updateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateButtonActionPerformed
        // TODO add your handling code here:
        new updatePatientRecord().setVisible(true);
    }//GEN-LAST:event_updateButtonActionPerformed

    private void hospitalInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hospitalInfoActionPerformed
        // TODO add your handling code here:
        new aboutHospital().setVisible(true);
    }//GEN-LAST:event_hospitalInfoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addPaitentButton;
    private javax.swing.JButton addressButton;
    private javax.swing.JLabel backgroundHome;
    private javax.swing.JButton exitButton;
    private javax.swing.JButton historyPatient;
    private javax.swing.JButton hospitalInfo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton updateButton;
    // End of variables declaration//GEN-END:variables
}
